### ISSUE TITLE
Create team logo and t-shirt

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#11]
## User story
1. As a software development team
2. We want to have a team logo and a t-shirt with the logo on it
3. So that our team has a unique identity

## Acceptance criteria
* Design a team logo
* Create a t-shirt design with our logo on [Shirtinator](https://shirtinator.de) (select the Standard Bio (Organic) type of T-shirt)
* Add the link to the t-shirt design to the planning document (this link may be a link to a shopping cart)
* Every team member submits his/her t-shirt preferences in this [survey](https://forms.gle/rdXqbq1WSFjwHkSx8)

## Definition of done (DoD)
* All acceptance criteria were met
* Agreement on a logo
* Link to the t-shirt design exists in planning document

**Comment by eubec** [comment]
Tshirt we agreed on (example):

![Image](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/148374350/995b4dc8-7723-4c58-a606-b50a239aef63)

**Comment by eubec** [comment]
Team logo we agreed on:

![Image](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/148374350/c233b4c3-ce28-4956-8eeb-4b33d295a229)

**Comment by eubec** [comment]
T-shirt design we agreed on: https://www.shirtinator.de/loadBasket/UI1hycWOPLd

**Comment by krutarth4** [comment]
This issue is no more needed
