### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#15]
## User story
1. As an extern developer
2. I need to see what purpose the project serves
3. So that I can decide if it helps to solve my problem

## Acceptance criteria

- [x] README.md contains a description of the project
- [x] README.md contains software components and functionality
- [x] README.md contains how to built/initialize everything

## Definition of done (DoD)
* All acceptance criteria were met

**Comment by ingunnaf** [comment]
I added it for the backend now
