### ISSUE TITLE
Agree on core technologies and familiarize with them

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#17]
## User story
1. As a software development team
2. We need to agree on core technologies and familiarize with them
3. So that all software developers can start to work on the project efficiently

## Acceptance criteria
* The following technologies could be considered for the project
   * Frontend: JavaScript/React or TypeScript/Angular
   * Backend: Java/Spring Boot or Python/Flask
   * Data Processing/Pipelining: Apache Airflow (others possible)
   * Infrastructure as Code: Terraform or Ansible
   * Container Orchestration: Kubernetes
   * Storage for raw data: Amazon S3
   * Storage for meta data: Elasticsearch or MongoDB. PostgreSQL or MySQL are also possible, but are rather not recommended by the industry partner.
   * Authentication Tool: Keycloak or Okta
* Software developers familiarize themselves with these technologies and create a pros and cons list
* All important findings and sources on a technology are documented in the [technology-wiki.md](https://github.com/amosproj/amos2023ws04-pipeline-manager/blob/main/Documentation/technology-wiki.md)

## Definition of done (DoD)
* Technologies are selected based on the pro and con list
* Software developers are familiar with the selected technologies

**Comment by eubec** [comment]
Access to the AWS Cloud is provided to each of us by the Industry Partner.
I have forwarded our email addresses to Stefan so he can do this.

**Comment by eubec** [comment]
Frontend: Angular
Backend: Python/Flask
Authentication: Keycloak
IaC: Terraform
Data Processing/Pipelining: Apache Airflow

**Comment by ingunnaf** [comment]
For the Definition of Done: a list of how we evaluated Python / Java

Python: better for compatibility with Apache Airflow ->
good to use one language across the backend for ease of switching between tickets,
Flask is a simple framework that is easy to understand

Java: preferred by our industry contact, more devs in our team are familiar with it

**Comment by krutarth4** [comment]
This issue is also completed
