### ISSUE TITLE
Upload csv-file

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#31]
## User story
1. As a user
2. I want to upload a csv file in a GUI
3. So that my file gets stored

## Acceptance criteria
- [x] After hitting SELECT, the user's file explorer opens and the user selects his file
- [x] Only csv files are allowed to be selected
- [x] After hitting UPLOAD, the selected csv file is send to the backend for storage
- [ ] The successful upload of a file is indicated by a success message
- [x] Calls the backend service for uploading the csv file into S3 Bucket

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* Important parts have been documented in the technology wiki
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by krutarth4** [comment]
@CAgcoder Hey I will be working on this one , you can try to get login up

**Comment by Elementator** [comment]
create a endpoint for uploading file data /upload/file
 - add filter for specific file types, e.g. csv, txt // maybe postponed
 - add error / and success massages if the endpoint failes
 create a service that uploads file to an s3 bucket
 - should be able to upload a file
 - and handle errors if connection is not there, or 
 upload error happend. 
 To test it you can use postman, or you can add a form-select field in templates

**Comment by Elementator** [comment]
get presigned url from backend

**Comment by Elementator** [comment]
merge to main
