### ISSUE TITLE
Backend inital setup

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#33]
## User story
1. As a software developer
2. I want to create an initial version of the backend
3. So that everything is setup for implementing first services

## Acceptance criteria
- When starting the application, a web server starts up
- Initialize Backend in a separate docker container
- Initialization is documented in README.md

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* Important parts have been documented in the technology wiki
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by eubec** [comment]
## Subtasks

- [ ] subtask 1
- [ ] subtask 2

**Comment by Elementator** [comment]
- [ ] https://github.com/amosproj/amos2023ws04-pipeline-manager/issues/34
- [ ] https://github.com/amosproj/amos2023ws04-pipeline-manager/issues/35

**Comment by Elementator** [comment]
Missing document for how to run it

**Comment by Keldami** [comment]
Readme/documentation is missing

**Comment by krutarth4** [comment]
@sravanthidatla78 @bhanuPrakashMa  do you have any documentation available, I would love to take a look how backend is coming along
