### ISSUE TITLE
Setup MongoDB

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#35]
## User story
1. As a software developer
2. I need a MongoDB
3. So that the metadata of an user's raw data can be stored

## Acceptance criteria
* Initialize MongoDB in a separate docker container
* Initialization is documented in README.md

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* Important parts have been documented in the technology wiki
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by Keldami** [comment]
Readme/Documentation is missing. 

dockerfile for global docker-compose is missing
