### ISSUE TITLE
Homework 2: Software architecture

### ISSUE THREAD

**Issue by Elementator** [amosproj/amos2023ws04-pipeline-manager#36]
## Prepare a description of the planned software architecture
include ...
- [x] An overview diagram of runtime components (one page)
- [x] An overview diagram of code components (one page)
- [x] A summary of the underlying technology stack (one page)
- [x] A textual explanation of the diagrams and choices (one page)

## Definition of Done
* Uploaded in deliverables folder

**Comment by ingunnaf** [comment]
https://www.figma.com/file/phTjB28fNUrzYSoKDeRDdp/Pipeline-Manager?type=whiteboard&node-id=0-1&t=PJBLRm6fO2lgusM9-0

**Comment by eubec** [comment]
Here is the architecture example proposed by the Industry Partner in the first meeting:

![Image](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/148374350/c19dd093-8965-42b2-bf93-218878f97485)

There also exists a drawio file (see in slack channel)

**Comment by krutarth4** [comment]
@eubec I am closing this issue as it has been finished and archived
