### ISSUE TITLE
Store csv file in S3 bucket

### ISSUE THREAD

**Issue by Elementator** [amosproj/amos2023ws04-pipeline-manager#37]
## User story
1. As a software developer
2. I want to provide a backend service that stores a csv file in the S3 bucket
3. So that it can be retrieved at a later point

## Acceptance criteria
- [x] Backend provides a api endpoint that receives a csv file
- [x] Backend then stores the csv file in a S3 bucket

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* Important parts have been documented in the technology wiki
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by Keldami** [comment]
3. Create an API enpoint for a file upload, e.g. file servie -> as generic as possible.
4. s3bucket service that handles the file and saves it. 
	- send file directly to s3bucket ??
	- send file metadata to backend to save it into mongodb
5. the file metadata is saved in the mongodb database as own filemetaData entity 

File Data entity
id
location: s3bucekt download link
fileName: 
fileSize:

**Comment by krutarth4** [comment]
@Keldami @ingunnaf Hey whats the plan for uploading file 

I was thinking it is better to upload directly from frontend and send a http call request with the S3 bucket link where exactly the file is stored, as it saves overhead of sending file to backend again

**Comment by ingunnaf** [comment]
Hello! I don't get notifications about comments here so text me on Slack if you want to reach me faster:) I didn't see you comment until now so I added it as a backend endpoint, and opened a MR it now

**Comment by eubec** [comment]
I think it would be better to have all the logic centralized in the backend. Also keep in mind that in this case the frontend has to do more tasks, such as sending the raw data to the data pipeline. This means that there are already two calls that the frontend would have to make. We should make sure that the frontend has to perform as few tasks as possible in order to ensure high performance.
