### ISSUE TITLE
Start data pipeline processing

### ISSUE THREAD

**Issue by Elementator** [amosproj/amos2023ws04-pipeline-manager#40]
## User story
1. As a software developer
2. I want start processing the csv file in the data pipeline
3. So that I get additional information on the csv file

## Acceptance criteria

- [ ] Start data pipeline processing with csv file
- [ ] Return the result to backend or store it in database

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by krutarth4** [comment]
@eubec This has been already done, and the implementation is already in main
