### ISSUE TITLE
Create use case diagram

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#45]
## User story
1. As a software development team
2. We want to create a use case diagram
3. So that everyone understands by which user role and how the application is to be used

## Acceptance criteria
* Create use case diagram (preferably with [draw.io](https://app.diagrams.net/))
* Upload in [documentation folder](https://github.com/amosproj/amos2023ws04-pipeline-manager/tree/main/Documentation)

## Definition of done (DoD)
* All acceptance criteria were met

**Comment by Elementator** [comment]
![Image](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/27633886/cde55c90-8981-4f69-ac1e-76cf68056ff0)
