### ISSUE TITLE
Download function in GUI

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#50]
## User story
1. As a user
2. I want to download a csv-file
3. So that I can work with it

## Acceptance criteria

- [x] Working area screen of the GUI is expanded by a csv-file download function
- [x] Working area shows all csv files currently stored in S3 Bucket (maybe 10 per page?)
- [x] Working area provide download function for each csv file showed
- [ ] Working area shows metadata of the stored csv file
- [ ] Optional: Download all Button

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* Important parts have been documented in the technology wiki
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by Elementator** [comment]
merge to main
