### ISSUE TITLE
Log-in function in GUI

### ISSUE THREAD

**Issue by eubec** [amosproj/amos2023ws04-pipeline-manager#51]
## User story
1. As a user
2. I want to log-in into the application
3. So that I have access to my data

## Acceptance criteria
* User can provide his username and password via a log-in screen in the frontend
* If the log-in was successful, the frontend displays the working area screen of the GUI
* If the log-in failed, the frontend should display a corresponding message to the user

## DoD general criteria
* Feature has been fully implemented
* Feature has been tested
* Feature has been merged into the main branch
* Important parts have been documented in the technology wiki
* All acceptance criteria were met
* Product owner approved features
* Developers agreed to release

**Comment by Elementator** [comment]
research other login methods
