### ISSUE TITLE
SD's Issue Guideline

### ISSUE THREAD

**Issue by krutarth4** [amosproj/amos2023ws04-pipeline-manager#54]
## User story
1. As a SD
2. I want / need to create an issue
3. So that the project sprint runs smooth.

## Acceptance criteria
* @Elementator agrees to it.
* @eubec agrees to it.
* Have been explained by PO's in next sprint

## Definition of Done
* All acceptance criteria were met

**Comment by krutarth4** [comment]
# Issue Guidelines for SD

## **Purpose**

The purpose of this guideline is to provide a structured approach for Software Developers (SD) when creating an issue on GitHub. This ensures that Product Owners (PO) can easily understand the context, prioritize tasks effectively, and maintain clear communication throughout the development process.

## **Step 1: Issue Creation**

### **1.1 Title**

Create a concise and descriptive title for the issue. Use imperative language to clearly state what needs to be done.

### **1.2 Template**

Fill in the issue template with all the relevant information. Include details such as:

- **Description**: Clearly articulate the problem, enhancement, or task.
- **User story** : Outline the expected outcome after the issue is resolved.
- **Acceptance criteria** : Describe the aim of the issue and define the acceptance crieria.
- **Steps to Reproduce Bug (if applicable)**: Provide step-by-step instructions for reproducing the issue.

## **Step 2: Tags and Milestone**

### **2.1 Tags**

Select appropriate tags that categorize the issue. Common tags may include:

- **`bug`**: For bug reports.
- **`enhancement`**: For new features or improvements.
- **`documentation`**: For issues related to documentation.
- **`help wanted`**: If additional assistance is needed.

### **2.2 Milestone**

Assign the issue to the appropriate milestone if applicable. This helps in organizing and tracking the progress of features or tasks within a specific release.

## **Step 3: Mention Product Owners**

### **3.1 Tagging**

Mention the relevant Product Owners in the issue description using the **`@username`** syntax to notify them of the new issue.

### **3.2 Clarification**

Seek clarification or input from the Product Owners if any details are unclear. Ensure that they are aware of the issue and its significance.

## **Step 4: Backlog Confirmation**

### **4.1 Product Owner's Review**

Product Owners review the issue and, if accepted, move it to the appropriate backlog. If rejected or requires changes, they communicate the feedback to the Software Developer.

### **4.2 Confirmation to SD**

Once an issue is accepted and moved to the backlog, Product Owners confirm this with a comment on the issue. This serves as an acknowledgment for the Software Developer to start working on it.

## **Step 5: Development**

### **5.1 Assignee**

The Software Developer assigned to the issue starts working on it promptly.

### **5.2 Progress Updates**

Provide regular updates on the progress of the issue. If facing challenges or delays, communicate them early to avoid misunderstandings.

Following this guideline ensures a smooth and efficient workflow, fostering clear communication between Software Developers and Product Owners throughout the development process.

**Comment by krutarth4** [comment]
@eubec and @Elementator would be great if you can provide me with feedback !! I want to publish it as soon as possible !

**Comment by krutarth4** [comment]
Also I just tagged the issue for our project and it has been added to feature board as a no status project

**Comment by Elementator** [comment]
It looks good to me. 
One thing what I think is pretty important, is the description/context of the issue. 

Since we PO are not working on the code, we are not that familiar with the technologies (e.g I'm don't know S3 Bucket, so I created an issue where file size, upload date and file type should be stored in MongoDB, although S3 Bucket already has these 3 metadata).
So without a good description/context we might not understand why it is an issue or what to do with it.

It would also be good if SD would look over the issues that we PO create and gives us feedback accordingly (either by commenting on the issue or message us directly) in case we missunderstood the technologies or the software architecture

**Comment by krutarth4** [comment]
@Elementator Yeah the SD will be providing with the initial description where and why do we need this ! Will add it in the readme
