### ISSUE TITLE
Database to store insights/metadata

### ISSUE THREAD

**Issue by Elementator** [amosproj/amos2023ws04-pipeline-manager#6]
## User story
1. As a user
2. I want to store insights and metadata from raw data
3. So that I can analyse and retrieve the raw data at any time

## Acceptance criteria

- [ ] Raw data's metadata stored
- [ ] Insights of raw data stored
- [ ] Can do SQL request

## Definition of done (DoD)

- [ ] Metadata stored (size, upload date, file type, name)
- [ ] Location of raw data
- [ ] Insights stored with link to raw data

New table for each insight? Or multiple columns?

**Comment by krutarth4** [comment]
Not required and doesn't provide direction towards next sprint
