### ISSUE TITLE
Frontend and Apache Airflow are not reachable when typing docker-compose up

### ISSUE THREAD

**Issue by ingunnaf** [amosproj/amos2023ws04-pipeline-manager#78]
**Describe the bug**
I pulled all updates from main and typed "docker-compose up" in terminal. All containers build and start up successfully, but when trying to reach the frontend at localhost:4200, I got the error "Safari can't Connect to the Server. Safari can't open the page 'localhost:4200' because Safari can't connect to the server 'localhost'". I also tried in google chrome, and got this error: 

"This site can’t be reached 
localhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED"

However, I am able to reach the backend at localhost:8000. 

**To Reproduce**
1. Checkout the main branch and pull all updates.
2. Type docker-compose up in terminal
3. Try to go to localhost:4200 in your browser

**Expected behavior**
I expect to see the frontend in the browser. 

**Screenshots**
![Screenshot 2023-11-18 at 17 27 48](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/16457358/92ee035e-7a0c-482a-8037-aae9f61ac350)

![Screenshot 2023-11-18 at 17 37 58](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/16457358/6d9e48a0-8652-41e0-9e45-42dae20d6ff6)
![Screenshot 2023-11-18 at 17 38 02](https://github.com/amosproj/amos2023ws04-pipeline-manager/assets/16457358/219d1f59-bda7-4ab4-9871-b20ff7ca48be)

**Desktop (please complete the following information):**
 - OS:  iOS, intel
 - Browser [chrome and safari]

**Comment by ingunnaf** [comment]
When running the test branch now, I first got errors regarding the requirements.txt file where there is a missing =

After fixing this typo, I cannot reach backend or frontend

**Comment by krutarth4** [comment]
@ingunnaf as I mentioned don't go through the test branch look at the documentation branch which also has some instruction on how to run everything. And after that you have an error Pin me
