### ISSUE TITLE
Store raw data's metadata in a database

### ISSUE THREAD

**Issue by Elementator** [amosproj/amos2023ws04-pipeline-manager#8]
## User story
1. As a user
2. I want the metadata stored in a database
3. So that retrieve data later

## Acceptance criteria

- [ ] Store metadata in database

## Definition of done (DoD)

- [ ] Stored upload date
- [ ] Stored file type
- [ ] Stored size

**Comment by krutarth4** [comment]
Duplicate issue, and is not required
