### ISSUE TITLE
Keycloak Authentication

### ISSUE THREAD

**Issue by Keldami** [amosproj/amos2023ws04-pipeline-manager#91]
### Issue
All authentication requests are validated via some token. That is coming from a Keycloak instance. 

### DoD general criteria
- Feature has been fully implemented
- Feature has been tested
- Feature has been merged into the main branch
- Important parts have been documented in the technology wiki
- All acceptance criteria were met
- Product owner approved features
- Developers agreed to release

**Comment by Elementator** [comment]
Have another ticket for it
